chispa/dataframe_comparer.py
tests/test_dataframe_comparer.py

Adding the capability to add dataframe transformers to the assert_df_equality method. This helps take care of a few use cases such as :
1. Sorting of columns before comparing the schema
2. Conversion of columns from Integer type to Long so that a test dataframe loaded from csv can be compared against actual
Thanks for building chispa!

Add dataframe transformers to assert_df_equality

---

chispa/__init__.py
poetry.lock
pyproject.toml

if `findspark` isn't installed, then fallback to the "manual" setup by looking into `SPARK_HOME`. I deliberately didn't put `findspark` as required dependency, although we can move it there...

try to use findspark to find PySpark installation

---

chispa/schema_comparer.py

The correct `zip` is being clobbered by a naive `zip` when displaying the table.
```
chispa.schema_comparer.SchemasNotEqualError:
+----------------------------------------------------------+----------------------------------------------------------+
|                         schema1                          |                         schema2                          |
+----------------------------------------------------------+----------------------------------------------------------+
|            StructField(name,StringType,true)             |            StructField(name,StringType,true)             |
|           StructField(website,StringType,true)           |           StructField(website,StringType,true)           |
+----------------------------------------------------------+---------- …
```

Fix the schema zipping for display

---

chispa/dataframe_comparer.py
chispa/schema_comparer.py
tests/test_dataframe_comparer.py

Fixes #17 
Fixes #18 
Fixes #10

Remove duplicate code in dataframe comparer

---

pyproject.toml

This changes the build backend to `poetry-core`[^1].
> intended to be a light weight, fully compliant, self-contained package allowing PEP 517 compatible build frontends to build Poetry managed projects
[^1]: https://github.com/python-poetry/poetry-core

build: change build-backend to poetry-core

---

README.md

The `--dev` flag is deprecated. 
Poetry warns to use `-G dev` or `--group dev` to add dependencies to the `dev` dependency group.

docs(README): update poetry installation command

---

chispa/dataframe_comparer.py
chispa/number_helpers.py
chispa/row_comparer.py
tests/test_dataframe_comparer.py

W.ref.to https://github.com/MrPowers/chispa/issues/22 
Added the following options to `assert_approx_df_equality` function.
`1. allow_nan_equality
2. ignore_column_order
3. ignore_row_order
4. ignore_schema`
The option `ignore_nullable` is already present. 
This is done  by making use of the existing `assert_df_equality` function. 
Also added 3 tests on approx dataframe comparision to test the new options added.
All tests are passing.

Provide the options in df_equality into approx_df_equality as well

---

chispa/__init__.py
chispa/dataframe_comparer.py
chispa/rows_comparer.py
tests/test_dataframe_comparer.py
tests/test_rows_comparer.py

This PR introduced a bug: https://github.com/MrPowers/chispa/pull/32
We've been chatting about the bug in this issue: https://github.com/MrPowers/chispa/issues/54
Here's the current buggy API for comparing DataFrame equality without considering the schema: `assert_df_equality(df1, df2, ignore_schema=True)`
Here's the proposed new API: `assert_basic_rows_equality(df1.collect(), df2.collect())`
Let me know what you think.

Add rows comparer

---

README.md
chispa/bcolors.py
chispa/dataframe_comparer.py
chispa/rows_comparer.py

Added a Boolean flag for `assert_df_equality` that when enabled, highlights the differences within rows. Example:
Usage: `assert_df_equality(df1, df2, underline_cells=True)`
Fixes #52
To assess any impact to performance, I ran some quick tests comparing `assert_df_equality` with `underline_cells` disabled and then enabled to compare.
- Spark on local
- Sample Dataframe was 10,000 rows
- Used `timeit` package, with 100 executions
No significant difference noted. Results show % change compared to baseline when `underline_cells` is disabled.
<table>
<thead>
<tr>
<th rowspan="2">Number of columns in both df1 and df2</th>
<th colspan="3">Number of changes from df1 to df2</th>
</tr>
<tr>
<th>20</th>
<th>150</th>
<th>300</th>
</tr>
</thead>
<tbody>
<tr>
<td>5</td>
<td>+0.24%</td>
<td>+0.77%</td> …

Highlight mismatching values option for assert_df_equality

---

chispa/__init__.py
chispa/dataframe_comparer.py
tests/conftest.py
tests/test_readme_examples.py

This pull request exposes a `Chispa` class that will make it easier to share instantiate project-level defaults and share them in the test suite.
Here's how users can currently use custom formatting in the configuration file:
```python
@dataclass
class MyFormats:
mismatched_rows = ["light_yellow"]
matched_rows = ["cyan", "bold"]
mismatched_cells = ["purple"]
matched_cells = ["blue"]
@pytest.fixture()
def my_formats():
return MyFormats()
```
Here's how the formats can be used
```python
def it_shows_assert_basic_rows_equality(my_formats):
...
assert_basic_rows_equality(df1.collect(), df2.collect(), formats=my_formats)
```
This is a bit tedious because the user needs to pass the formats for every function invocation in the test suite.
The new interface allows for the custom formats to be …

New Chispa interface

---

.github/actions/setup-poetry-env/action.yml
.github/workflows/ci.yml
.github/workflows/mkdocs.yml
poetry.lock
pyproject.toml

This PR builds upon [this PR](https://github.com/MrPowers/chispa/pull/80). When that is merged I can update this branch to better reflect the changes in "Files changed".
Related issue: https://github.com/MrPowers/chispa/issues/82
---
This PR adds testing against multiple Python versions, updates some of the mkdocs dependencies, and changes the trigger of the CI checks to run on each pull request and on each commit to master (i.e. merging a PR). For an example run, see [here](https://github.com/fpgmaas/chispa/actions/runs/6564589223), or approve the workflow run on this PR.
This also adds a check for the `poetry.lock` file; to prevent issues like #107 
I think this can be helpful, let me know what you think of the proposal!

Add unit tests for multiple python versions to CI stage

---

pyproject.toml

This proposes to add some fields to `pyproject.toml`. The main benefit of this will be an improved PyPI page, since currently [that is very empty](https://pypi.org/project/chispa/). 
It also adds @SemyonSinchenko and myself as maintainers and proposes to use full names instead of github handles in the `authors` and `maintainers` fields.

Improve pyproject.toml

---

mkdocs.yml
poetry.lock
pyproject.toml

As proposed in issue https://github.com/MrPowers/chispa/issues/101, this adds the theme mkdocs-material to the documentation of the project. Color scheme is subjective and can easily be changed of course :)

Add mkdocs-material

---

NOTICE-binary.md

We need to follow licenses of our dependencies little more strictly. I'm not 100% sure how to do it, but I think adding NOTICE-binary is a good first step.
Close #116

feat: NOTICE-binary file

---

README.md

Using of links to `raw.githubuser` instead of links to file-history in git.
It fixes the problem with links (#135): https://semyonsinchenko.github.io/chispa/
Close #135

Fix all the links in README

---

.github/workflows/ci.yml
Makefile
chispa/__init__.py
chispa/bcolors.py
chispa/column_comparer.py
chispa/dataframe_comparer.py
chispa/default_formats.py
chispa/formatting/format_string.py
chispa/formatting/formats.py
chispa/formatting/formatting_config.py
chispa/number_helpers.py
chispa/row_comparer.py
chispa/rows_comparer.py
chispa/schema_comparer.py
poetry.lock
pyproject.toml

This adds static typing with `mypy`. This makes it more clear to end users what expected arguments are, and helps us catch bugs earlier.
Based on top of https://github.com/MrPowers/chispa/pull/129, so this needs to be rebased and reviewd after that one is merged.

chore: add static typing with mypy

---

chispa/schema_comparer.py
tests/test_structfield_comparer.py

Follow up on #133. 
The ignore_metadata flag wasn't propagating properly for structfields containing an array of structfields.

fix ignore_metadata flag propagation for arrays of structs

---

README.md
chispa/__init__.py
chispa/dataframe_comparer.py
tests/test_dataframe_comparer.py

Add ignore_columns option to:
assert_df_equality()
assert_approx_df_equality()
Implementation for #140 
Often when comparing dataframes we have some columns which can / should be ignored during the equality check. E.g. timestamp columns, or UUID.
With the implementation of ignore_columns option in:
assert_df_equality(),
and
assert_approx_df_equality(),
functions, users can now specify columns to be ignoered during databrame comparison.

Add ignore_columns option to dataframe_comparer.py

---

chispa/schema_comparer.py
tests/test_schema_comparer.py

This PR addresses an issue with comparing dataframes that contain DecimalType columns.
When using assert_schema_equality with default flag values, strict type validation is required. However, enabling the ignore_nullable flag changes type validation to only check for type name equality. As a result, Decimal(10, 3) is considered equal to Decimal(5, 2).
This PR ensures that type attributes (e.g. precision and scale for DecimalType) are considered in the type comparison process.
Code example to reproduce existing behaviour:
```
from __future__ import annotations
from decimal import Decimal
from chispa.schema_comparer import assert_schema_equality
from pyspark.sql import SparkSession
from pyspark.sql import types as T
spark = …
```

Add strict data type comparison when nullability/metadata flags

---

chispa/dataframe_comparer.py
tests/test_dataframe_comparer.py

We discovered a subtle bug in the `assert_df_equality` function. When both `ignore_row_order` and `ignore_columns` are enabled (and optionally `ignore_column_order` as well), the transformation chain currently sorts the DataFrame rows using all columns (including those later dropped by `ignore_columns`). This leads to incorrect row alignment when the ignored columns actually affect tie-breaking in the sort. In real-world usage, this results in the cell-by-cell equality assertion mis-identifying rows as being in a different order—even though the final visible data (after dropping the ignored columns) should be identical.
What was done?
- A new unit test it_works_when_sorting_and_dropping_columns() has been added.
- The test creates two DataFrames that differ only in the order of values in …

BugFix: row ordering in assert_df_equality when using ignore_columns with ignore_row_order

---

README.md

Update the badges in the README. For an example, see [here](https://github.com/fpgmaas/chispa/blob/chore/badges/README.md).

chore: Update the badges in the README

---

chispa/__init__.py

`SchemasNotEqualError` is not exposed as part of the public API. It may be needed for exception handling.
For instance: 
```py
from chispa import SchemasNotEqualError, DataFramesNotEqualError, assert_df_equality
try:
assert_df_equality(
df1,
df2,
)
except (
DataFramesNotEqualError,
SchemasNotEqualError,
):
print("Handle exception")
```
Currently this exception may be imported from `chispa.schema_comparer` directly (unstable), but that is not best practice as the `chispa/__init__.py` file is what defines the public API (stable)

Expose `SchemasNotEqualError` in public API
